### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by elly179** [SteinOveHelset/interiorshop#2]
Hello. i cloned the sourcecode and i also did built up a virtual environment and activated it but when running the "python manage.py runserver" code , am getting the following errors.
Would you please help me fix it. Email:rllystanley@gmail.com

![error](https://user-images.githubusercontent.com/57063615/128602552-92af4e4d-8b3f-43e0-b784-283997d5e9da.PNG)

**Comment by SteinOveHelset** [comment]
Hi!
This comes from some changes in Django 3.2.
In your settings.py, use "apps.cart.apps.CartConfig" instead of "cart". And in your "apps/cart/apps.py", rename "cart" to "apps.cart" :-)
